// Generated by CoffeeScript 1.9.1
(function() {
  var array, canvas, context, draw, offsetX, offsetY, scale, size, socket, writeMessage;

  socket = io.connect();

  socket.on("connect", function() {
    return writeMessage("connect");
  });

  socket.on("disconnect", function() {
    return writeMessage("disconnect");
  });

  socket.on("draw", function(data) {
    return draw(data);
  });

  socket.on("message", function(text) {
    return writeMessage(text);
  });

  size = array = canvas = scale = offsetX = offsetY = context = null;

  draw = function(data) {
    var i, j, k, l, m, ref, ref1, ref2;
    if (data != null) {
      if (data.size != null) {
        size = data.size;
      }
      if (data.array != null) {
        array = data.array;
      }
    }
    canvas = document.getElementById("canvas");
    canvas.width = canvas.clientWidth;
    canvas.height = canvas.clientHeight;
    scale = Math.floor(Math.min(canvas.width, canvas.height) / (size + 2));
    offsetX = Math.floor((canvas.width - size * scale) / 2);
    offsetY = Math.floor((canvas.height - size * scale) / 2);
    context = canvas.getContext("2d");
    context.setTransform(scale, 0, 0, scale, offsetX, offsetY);
    context.fillStyle = "#afa";
    context.fillRect(0, 0, size, size);
    context.strokeStyle = "#0a0";
    context.lineWidth = 0.02;
    context.lineJoin = "round";
    context.beginPath();
    for (i = k = 1, ref = size; 1 <= ref ? k < ref : k > ref; i = 1 <= ref ? ++k : --k) {
      context.moveTo(i, 0);
      context.lineTo(i, size);
      context.moveTo(0, i);
      context.lineTo(size, i);
    }
    context.rect(0, 0, size, size);
    context.stroke();
    for (i = l = 0, ref1 = size; 0 <= ref1 ? l < ref1 : l > ref1; i = 0 <= ref1 ? ++l : --l) {
      for (j = m = 0, ref2 = size; 0 <= ref2 ? m < ref2 : m > ref2; j = 0 <= ref2 ? ++m : --m) {
        switch (array[i][j]) {
          case 'x':
            context.beginPath();
            context.arc(i + 1 / 2, j + 1 / 2, 0.4, 0, 2 * Math.PI);
            context.fillStyle = "#000";
            context.fill();
            context.strokeStyle = "#000";
            context.stroke();
            break;
          case 'o':
            context.beginPath();
            context.arc(i + 1 / 2, j + 1 / 2, 0.4, 0, 2 * Math.PI);
            context.fillStyle = "#fff";
            context.fill();
            context.strokeStyle = "#000";
            context.stroke();
        }
      }
    }
  };

  writeMessage = function(text) {
    console.log(text);
  };

  window.onclick = function(event) {
    var i, j;
    i = Math.floor((event.clientX - offsetX) / scale);
    j = Math.floor((event.clientY - offsetY) / scale);
    if ((0 <= i && i < size) && (0 <= j && j < size)) {
      socket.emit("click", i, j);
    }
  };

}).call(this);
